framework:
    # Deprecations for 7.0
    handle_all_throwables: true
    # cannot be disabled, because of https://github.com/nelmio/NelmioApiDocBundle/pull/2164
    annotations:
            enabled: true
    # ---------------------------

    exceptions:
        App\Validator\ValidationFailedException:
            log_level: debug

    secret: '%env(APP_SECRET)%'
    default_locale: en
    csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: App\Security\SessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        cookie_httponly: true
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

    mailer:
        dsn: '%env(MAILER_URL)%'

    validation:
        email_validation_mode: html5

when@dev:
    framework:
        mailer:
            dsn: 'null://null'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
        mailer:
            dsn: 'null://null'
