kimai:

    # Settings for the user management and login forms
    user:
        registration: true
        password_reset: true

    # All configs related to timesheet and record management
    timesheet:

        # Whether we display start and end time columns (false) or durations only (true).
        # Setting this to true will also change the "edit timesheet" forms, more infos available in the configurations docu.
        duration_only: false

        # Rounding rules are used to round the begin & end dates and the duration for timesheet records.
        # The "default" rule will round "begin" down and "end" up to the full minute, the "duration" will not be rounded.
        # Please read var/docs/configurations.md to find out more about rounding rules
        rounding:
            default:
                days: ['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
                begin: 1
                end: 1
                duration: 0

        # If you want to apply different hourly rates for specific weekdays, you can uncomment the "rates" configuration.
        # The "weekend" rule will add 50% to each timesheet entry that will be recorded on "saturdays" or "sundays".
        # Please read var/docs/configurations.md to find out more about rates rules
        # rates:
        #    weekend:
        #        days: ['saturday','sunday']
        #        factor: 1.5

    # All configs related to the invoice administration
    invoice:
        renderer:
            default: 'App\Controller\InvoiceController::invoiceAction'
            timesheet: 'App\Controller\InvoiceController::timesheetAction'
        calculator:
            default: 'App\Invoice\DefaultCalculator'
            short: 'App\Invoice\ShortInvoiceCalculator'
        number_generator:
            default: 'App\Invoice\DateNumberGenerator'

    # Language specific settings, like the date formats
    languages:
        de:
            date_short: 'd.m.Y'
        en:
            date_short: 'Y-m-d'
        ru:
            date_short: 'd.m.Y'

    # timesheet calendar configuration
    calendar:
        week_numbers: true
        day_limit: 4
        businessHours:
            days: [1, 2, 3, 4, 5]
            begin: '08:00'
            end: '20:00'

        # You can configure unlimited google calendars to display events for your company (e.g. holidays)
        # Please read var/docs/configurations.md to find out more about calendar integration
        # google:
        #     api_key: 'your-restricted-google-api-key'
        #     sources:
        #         holidays:
        #             id: 'de.german#holiday@group.v.calendar.google.com'
        #             color: '#ccc'

    # theme related settings, will be available as twig settings
    theme:
        # display a warning color if the user has at least X active recordings
        active_warning: 3
        # fallback color for all widgets that don't have a dedicated color
        # possible options: blue, black, purple, yellow, red, green
        box_color: 'green'
