twig:
#    form_themes:
#        - "bootstrap_3_layout.html.twig"
#        - "form/fields.html.twig"
    globals:
        kimai_context:
            date_1: "d.m.Y"         # used for display in timesheets
            box_color: "green"      # a color for ???
            active_warning: 3       # display a warning color if the user has at least X active recordings
