kimai:
    timesheet:
        rounding: 15
    invoice:
        renderer:
            default: 'App\Controller\InvoiceController::invoiceAction'
            timesheet: 'App\Controller\InvoiceController::timesheetAction'
        calculator:
            default: 'App\Invoice\DefaultCalculator'
            short: 'App\Invoice\ShortInvoiceCalculator'
        number_generator:
            default: 'App\Invoice\DateNumberGenerator'

twig:
    globals:
        kimai_context:
            date_1: "d.m.Y"         # used for display in timesheets
            box_color: "green"      # a color for ???
            active_warning: 3       # display a warning color if the user has at least X active recordings
            control_sidebar:        # all tabs in the control sidebar
                settings:
                    icon: gears
                    controller: 'App\Controller\SidebarController::settingsAction'
                home:
                    icon: question-circle-o
                    template: sidebar/home.html.twig
