nelmio_api_doc:
    models:
        use_jms: true
        names:
            - { alias: CustomerEntity,          type: App\Entity\Customer,                      groups: [Default, Entity, Customer] }
            - { alias: ProjectEntity,           type: App\Entity\Project,                       groups: [Default, Entity, Project] }
            - { alias: ActivityEntity,          type: App\Entity\Activity,                      groups: [Default, Entity, Activity] }
            - { alias: TimesheetEditForm,       type: App\Form\TimesheetEditForm,               groups: [Default, Entity, Timesheet] }
            - { alias: TimesheetEntity,         type: App\Entity\Timesheet,                     groups: [Default, Entity, Timesheet] }
            - { alias: UserEntity,              type: App\Entity\User,                          groups: [Default, Entity, User] }
    areas:
        path_patterns:
            - ^/api(?!/doc)
    documentation:
#        host: '{{hostname}}'
        schemes: [http, https]
        info:
            title: Kimai 2 - API Docs
            description: REST API description for the Kimai 2 time-tracking software. Do not rely on the example values/models, they are currently generated wrong. Please fetch the request and response structure from the API itself.
            version: 0.2
#        parameters:
#            hostname:
#                name: hostname
#                in: url
#                description: the hostname where your api runs
#                required: true
#                type: string
        securityDefinitions:
            X-AUTH-USER:
                type: apiKey
                description: 'Value: {Username}'
                name: X-AUTH-USER
                in: header
            X-AUTH-TOKEN:
                type: apiKey
                description: 'Value: {API Token}'
                name: X-AUTH-TOKEN
                in: header
        security:
            - X-AUTH-USER: []
            - X-AUTH-TOKEN: []
