config:
  repository: https://github.com/butu/kimai
hosts:
  kimai.webprofil.at.mars.webprofil.at:
    host: kimai.webprofil.at.mars.webprofil.at
    branch: main
    remote_user: c594983_w732_ssh1
    http_user: c594983_w732_ssh1
    forwardAgent: false
    deploy_path: /web
    labels:
      stage: prod
