App\Entity\Timesheet:
    exclusion_policy: All
    custom_accessor_order: [id, begin, end, duration, rate, activity, project, user, description, fixedRate, hourlyRate, exported]
    properties:
        id:
            include: true
            groups: [Default]
        begin:
            exclude: true
        end:
            exclude: true
        duration:
            include: true
            groups: [Default]
        description:
            include: true
            groups: [Default]
        rate:
            include: true
            groups: [Default]
        fixedRate:
            include: true
            groups: [Entity]
        hourlyRate:
            include: true
            groups: [Entity]
        exported:
            include: true
            groups: [Entity]
        activity:
            exclude: true
        project:
            exclude: true
        user:
            exclude: true
    virtual_properties:
        getBegin:
            serialized_name: begin
            exp: "object.getBegin() === null ? null : object.getBegin()"
            type: DateTime
            groups: [Default]
        getEnd:
            serialized_name: end
            exp: "object.getEnd() === null ? null : object.getEnd()"
            type: DateTime
            groups: [Default]
        getActivity:
            serialized_name: activity
            exp: "object.getActivity() === null ? null : object.getActivity().getId()"
            type: integer
            groups: [Default]
        getProject:
            serialized_name: project
            exp: "object.getProject() === null ? null : object.getProject().getId()"
            type: integer
            groups: [Default]
        getUser:
            serialized_name: user
            exp: "object.getUser().getId()"
            type: integer
            groups: [Default]
