App\Entity\Project:
    exclusion_policy: All
    custom_accessor_order: [id, name, comment, visible, budget, orderNumber, customer, fixedRate, hourlyRate]
    properties:
        id:
            include: true
            groups: [Default]
        name:
            include: true
            groups: [Default]
        comment:
            include: true
            groups: [Entity]
        visible:
            include: true
            groups: [Default]
        budget:
            include: true
            groups: [Entity]
        orderNumber:
            include: true
            groups: [Entity]
        fixedRate:
            include: true
            groups: [Default]
        hourlyRate:
            include: true
            groups: [Default]
        customer:
            include: false
            exclude: true
            groups: [Default]
    virtual_properties:
        getCustomer:
            serialized_name: customer
            exp: "object.getCustomer() === null ? null : object.getCustomer().getId()"
            type: integer
            groups: [Default]
