name: 'Website update'
on:
  workflow_dispatch:
    inputs:
      kimai_version:
        description: 'The Kimai version to update the website for'
        required: true
  release:
    types: [released]

jobs:
  build:
    name: Trigger version update for website
    runs-on: ubuntu-latest
    steps:
      - name: "Determine Version"
        run: |
          input="${{ github.event.inputs.kimai_version }}"

          # Determine between manual trigger and release event
          if [ -z "$input" ]; then
              echo "No input provided, using release tag"
              echo "kimai_version=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
              echo "Using input provided: $input"
              echo "kimai_version=$input" >> $GITHUB_ENV
          fi

      - name: Emit repository_dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.WEBSITE_ACCESS_TOKEN }}
          repository: kimai/www.kimai.org
          event-type: kimai_release
          client_payload: '{"kimai_version": "$kimai_version"}'
